# Generated by Django 5.1.5 on 2025-02-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clients",
            options={
                "ordering": ["email", "full_name"],
                "permissions": [("can_bloc_clients", "Can bloc clients")],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
