# Generated by Django 5.1.5 on 2025-02-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_alter_clients_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clients",
            options={
                "ordering": ["email", "full_name"],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
