# Generated by Django 5.1.5 on 2025-02-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_campaignattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-end_time'], 'permissions': [('can_disable_mailing', 'Can disable mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
