# Generated by Django 5.1.5 on 2025-02-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_campaign_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="sent_messages",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="successful_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="unsuccessful_attempts",
            field=models.IntegerField(default=0),
        ),
    ]
